sudo: required
services:
  - docker

before_install: 
  - docker build -t tnilesh02/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tnilesh02/docker-react npm run test -- --coverage