sudo: required
services:
  - docker

before_install: 
  - docker build -t tnilesh02/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tnilesh02/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-basic-react"
  env: "Docker-basic-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-689614830162"
  bucket_path: "Docker-basic-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"